// <auto-generated />
namespace BlogEngine.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BlogContext1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BlogContext1));
        
        string IMigrationMetadata.Id
        {
            get { return "201512060439082_BlogContext1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
