// <auto-generated />
namespace HospitalApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class annotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(annotations));
        
        string IMigrationMetadata.Id
        {
            get { return "201601091445562_annotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
