//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace testdbmodel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentId { get; set; }
        public string UserName { get; set; }
        public System.DateTime CommentDate { get; set; }
        public string Text { get; set; }
        public Nullable<int> News_Id { get; set; }
        public Nullable<int> NewsTag_TagId { get; set; }
    
        public virtual News News { get; set; }
        public virtual NewsTag NewsTag { get; set; }
    }
}
